import {Window} from 'happy-dom';
import {build} from 'esbuild';
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import assert from 'node:assert/strict';
const window=new Window({url:'http://localhost:4173/'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','Node','Event','MouseEvent','MutationObserver','localStorage','location','history','FormData'])Object.defineProperty(globalThis,k,{value:k==='window'?window:window[k],configurable:true,writable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.fetch=async()=>({ok:true,json:async()=>JSON.parse(await readFile('public/images.json','utf8'))});
window.scrollTo=()=>{};window.prompt=()=> '5';window.confirm=()=>true;
const temp='.sites-runtime/ui-check';await mkdir(temp,{recursive:true});
await build({entryPoints:['src/main.jsx'],bundle:true,format:'esm',platform:'node',external:['react','react-dom/*','react-router-dom','lucide-react'],outfile:temp+'/app.mjs',define:{'import.meta.env.VITE_API_URL':'undefined'},loader:{'.css':'empty'}});
document.body.innerHTML='<div id="root"></div>';
const {screen,fireEvent,waitFor,act}=await import('@testing-library/react');
await act(async()=>{await import('../'+temp+'/app.mjs')});
await waitFor(()=>assert(screen.getByText('Amul Taaza')));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Login'})));
await waitFor(()=>assert.equal(location.hash,'#/login'));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Admin',exact:true})));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Enter admin demo'})));
await waitFor(()=>assert(screen.getByText('Products & stock')));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'New product'})));
const dialog=screen.getByRole('dialog',{name:'Product editor'});
for(const [name,value] of Object.entries({id:'ui-test-sku',name:'UI test milk',detail:'1 litre',price:'45',stock:'10'}))fireEvent.change(dialog.querySelector('[name="'+name+'"]'),{target:{value}});
await act(async()=>fireEvent.submit(dialog.querySelector('form')));
await waitFor(()=>assert(screen.getByText('UI test milk')));
const row=screen.getByText('UI test milk').closest('article');
await act(async()=>fireEvent.click([...row.querySelectorAll('button')].find(b=>b.textContent.includes('Receive stock'))));
await waitFor(()=>assert(row.textContent.includes('15 in stock')));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Delete UI test milk'})));
await waitFor(()=>assert.equal(screen.queryByText('UI test milk'),null));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Web lab'})));
await waitFor(()=>assert(screen.getByText('Web lab, in practice.')));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Update count (0)'})));
await waitFor(()=>assert(screen.getByText('Class component updated: 1')));
await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Unmount component'})));
await waitFor(()=>assert(screen.getByText('Class component unmounted')));
await writeFile('docs/UI_TEST_RESULTS.json',JSON.stringify({status:'passed',checks:['catalog render','React Router login route','admin demo entry','create SKU','receive stock increments','delete unused SKU','lab route','class update lifecycle','class unmount lifecycle'],scope:'DOM interaction tests with happy-dom, not real-browser layout or pixel verification'},null,2));
console.log('9 DOM interaction checks passed');await window.happyDOM.abort();await rm(temp,{recursive:true,force:true});process.exit(0);
